### ISSUE TITLE
I can't build the project

### ISSUE THREAD

**Issue by lopesivan** [dgis/emu48android#20]
I would like to contribute to the project, but I can't build the project
How to compile??? as some files are not present, such as Ops.h, ops.h ...

I ran ./gradlew build, and logically set my sdk in local.properties

**Comment by dgis** [comment]
If you are trying to build with Linux/macos, you will have to, either duplicate ops.h in Ops.h, or fix the files by changing from:
#include "Ops.h"
into 
#include "ops.h"
because the issue is an inconstant include filename coming from the original Emu48 for Windows source code.
The same for the file "Opcodes.h"!
Each time update "app\src\main\cpp\core\*.*", I do not fix those issues, sorry.
